// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TennisMatchmaker.Data;

#nullable disable

namespace TennisMatchmaker.Api.Migrations
{
    [DbContext(typeof(TennisDbContext))]
    [Migration("20260903055127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TennisMatchmaker.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeaderId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.GroupMembership", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtNumber")
                        .HasColumnType("integer");

                    b.Property<int>("MatchType")
                        .HasColumnType("integer");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamAPlayer1Id")
                        .HasColumnType("integer");

                    b.Property<int>("TeamAPlayer2Id")
                        .HasColumnType("integer");

                    b.Property<int>("TeamBPlayer1Id")
                        .HasColumnType("integer");

                    b.Property<int>("TeamBPlayer2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.PairingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastPlayedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerAId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerBId")
                        .HasColumnType("integer");

                    b.Property<int>("TimesOpposed")
                        .HasColumnType("integer");

                    b.Property<int>("TimesPartnered")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAId", "PlayerBId")
                        .IsUnique();

                    b.ToTable("PairingHistories");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SkillLevel")
                        .HasPrecision(3, 1)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("RuleConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.SessionPlayer", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("SessionId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("SessionPlayers");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.GroupMembership", b =>
                {
                    b.HasOne("TennisMatchmaker.Models.Group", "Group")
                        .WithMany("PlayerMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisMatchmaker.Models.Player", "Player")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Match", b =>
                {
                    b.HasOne("TennisMatchmaker.Models.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Round", b =>
                {
                    b.HasOne("TennisMatchmaker.Models.Session", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Session", b =>
                {
                    b.HasOne("TennisMatchmaker.Models.Group", "Group")
                        .WithMany("Sessions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.SessionPlayer", b =>
                {
                    b.HasOne("TennisMatchmaker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisMatchmaker.Models.Session", "Session")
                        .WithMany("SelectedPlayers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Group", b =>
                {
                    b.Navigation("PlayerMemberships");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Player", b =>
                {
                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Round", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("TennisMatchmaker.Models.Session", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("SelectedPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
